### ISSUE TITLE
Comment is not closed 

### ISSUE THREAD

**Issue by babaJay23** [benahm/sfdx-mdt-plugin#3]
Getting this error comment is not closed when using this plug-in and only half of the deltas that are detected are put into the folder.

**Comment by benahm** [comment]
Hello can you provide more details about the error, the plugin should show you on which file the error occured 
Thanks

**Comment by babaJay23** [comment]
That’s one thing I wish for is more verbosity :) can you join a zoom meeting I can show you more than I can tell you. 


Regards, Jay

**Comment by benahm** [comment]
Hello @babaJay23 
Can you check with the new version 0.5.2
Regards
