### ISSUE TITLE
Does retrieve parse spaces in a profile name?

### ISSUE THREAD

**Issue by weytani** [benahm/sfdx-mdt-plugin#4]
Errors out as follows: `djr@redacted DOT-FHWA-MSAR % sfdx mdt:profile:retrieve -u redacted -p force-app/main/default/profiles/Community Field User - DOT Cloned.profile-meta.xml
 ›   Warning: sfdx-cli update available from 7.144.2 to 7.163.0.
ERROR running mdt:profile:retrieve:  Unexpected arguments: Field, User, -, DOT, Cloned.profile-meta.xml
See more help with --help`

**Comment by gatekepa** [comment]
Hi @weytani,
I don't believe this is an issue. To parse spaces, enclose the path in double-quotation marks to make a string. e.g.
`sfdx mdt:profile:retrieve -u redacted -p "force-app/main/default/profiles/Community Field User - DOT Cloned.profile-meta.xml"`

Hope this helps! I just used this myself :)

**Comment by benahm** [comment]
@gatekepa answered this issue ✅
