### ISSUE TITLE
La version sfdx-mdt-plugin 0.6.5 ne fonctionne pas

### ISSUE THREAD

**Issue by djoly42** [benahm/sfdx-mdt-plugin#5]
<img width="459" alt="Capture" src="https://user-images.githubusercontent.com/16212644/237063191-695a9acf-6207-4fe4-8fda-1b2b7f1a86ff.PNG">

![image](https://user-images.githubusercontent.com/16212644/237063397-f780ed73-75ba-4e50-ac4c-ee18537b66f4.png)

sfdx-cli/7.199.7 win32-x64 node-v18.16.0

**Comment by benahm** [comment]
Hello

Ok je vais checker, tu peux downgrade vers la version précédente avec 

sfdx plugins:install sfdx-mdt-plugin@0.6.4
